
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zhe
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        initComponents();
        selectData();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJK = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNIS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jrbLaki = new javax.swing.JRadioButton();
        jrbPerempuan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jtfKelas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaAlamat = new javax.swing.JTextArea();
        jtfTempatLahir = new javax.swing.JTextField();
        jdcTanggalLahir = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbSave = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jbClear = new javax.swing.JButton();
        jbRefresh = new javax.swing.JButton();
        jbEdit = new javax.swing.JButton();
        jbEdit1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelJam = new javax.swing.JLabel();
        jLabelTanggal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Alamat");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 430, 100, 20);

        jtfNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNISActionPerformed(evt);
            }
        });
        jPanel2.add(jtfNIS);
        jtfNIS.setBounds(10, 30, 270, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NIS");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 10, 30, 20);
        jPanel2.add(jtfNama);
        jtfNama.setBounds(10, 90, 270, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nama");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 70, 50, 20);

        bgJK.add(jrbLaki);
        jrbLaki.setText("Laki-laki");
        jPanel2.add(jrbLaki);
        jrbLaki.setBounds(10, 150, 90, 23);

        bgJK.add(jrbPerempuan);
        jrbPerempuan.setText("Perempuan");
        jPanel2.add(jrbPerempuan);
        jrbPerempuan.setBounds(90, 150, 120, 23);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Lahir");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 250, 120, 20);
        jPanel2.add(jtfKelas);
        jtfKelas.setBounds(10, 330, 270, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Kelas");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 310, 100, 20);
        jPanel2.add(jtfEmail);
        jtfEmail.setBounds(10, 390, 270, 30);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 370, 100, 20);

        jtaAlamat.setColumns(20);
        jtaAlamat.setRows(5);
        jScrollPane1.setViewportView(jtaAlamat);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 450, 270, 80);
        jPanel2.add(jtfTempatLahir);
        jtfTempatLahir.setBounds(10, 210, 270, 30);
        jPanel2.add(jdcTanggalLahir);
        jdcTanggalLahir.setBounds(10, 270, 270, 30);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Jenis Kelamin");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 130, 120, 20);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Tempat Lahir");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 190, 120, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 160, 290, 550);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(null);

        jbSave.setText("Save");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });
        jPanel3.add(jbSave);
        jbSave.setBounds(10, 10, 90, 40);

        jbDelete.setText("Delete");
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(jbDelete);
        jbDelete.setBounds(100, 10, 90, 40);

        jbClear.setText("Clear");
        jbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearActionPerformed(evt);
            }
        });
        jPanel3.add(jbClear);
        jbClear.setBounds(190, 10, 80, 40);

        jbRefresh.setText("Refresh");
        jbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(jbRefresh);
        jbRefresh.setBounds(280, 10, 80, 40);

        jbEdit.setText("Edit");
        jbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditActionPerformed(evt);
            }
        });
        jPanel3.add(jbEdit);
        jbEdit.setBounds(360, 10, 80, 40);

        jbEdit1.setText("Print");
        jbEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEdit1ActionPerformed(evt);
            }
        });
        jPanel3.add(jbEdit1);
        jbEdit1.setBounds(440, 10, 80, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(300, 110, 530, 60);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM BIODATA SISWA SMK TELKOM MALANG");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 660, 29);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("The Real Informatic Schools");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 50, 270, 29);

        jLabelJam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelJam.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJam.setText("Jam");
        jPanel1.add(jLabelJam);
        jLabelJam.setBounds(650, 60, 180, 17);

        jLabelTanggal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTanggal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTanggal.setText("Tanggal");
        jPanel1.add(jLabelTanggal);
        jLabelTanggal.setBounds(650, 30, 130, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 100);

        jPanel5.setBackground(new java.awt.Color(102, 255, 102));
        jPanel5.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ISIAN DATA SISWA");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(70, 0, 160, 50);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 109, 290, 50);

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));
        jPanel4.setLayout(null);

        jScrollPane2.setBackground(new java.awt.Color(153, 255, 153));

        jtTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Tanggal Lahir", "Jenis Kelamin", "Kelas", "Email", "Tempat Lahir", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtTabel);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 510, 500);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(300, 180, 530, 530);

        setSize(new java.awt.Dimension(855, 743));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(jdcTanggalLahir.getDate());
        String JK;
            if (jrbLaki.isSelected()) {
                JK = "L";
            } else {
                JK = "P";
            }
        if ("".equals(jtfNIS.getText()) || "".equals(jtaAlamat.getText()) || "".equals(jtfKelas.getText()) || "".equals(jtfNama.getText()) || "".equals(jtfEmail.getText()) || "".equals(jtfTempatLahir.getText()) || tanggal.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,tanggalLahir,JenisKelamin,Kelas,Email,tempatLahir,Alamat) "
                    + "VALUES('" + jtfNIS.getText() + "','" + jtfNama.getText() + "','"+ tanggal + "','"+ JK + "','"
                    + jtfKelas.getText() + "','" +jtfEmail.getText() + "','" +jtfTempatLahir.getText() + "','" + jtaAlamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbSaveActionPerformed

    private void jtfNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNISActionPerformed

    private void jtTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelMouseClicked
        // TODO add your handling code here:
        int baris = jtTabel.getSelectedRow();
        if (baris != -1) {
            jtfNIS.setText(jtTabel.getValueAt(baris, 0).toString());
            jtfNama.setText(jtTabel.getValueAt(baris, 1).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try {
                dateFormat = date.parse(jtTabel.getValueAt(baris, 2).toString());
            } catch (ParseException ex) {
                Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            jdcTanggalLahir.setDate(dateFormat);
            if ("Laki-laki".equals(jtTabel.getValueAt(baris, 3).toString())) {
                jrbLaki.setSelected(true);
            } else {
                jrbPerempuan.setSelected(true);
            }
            jtfKelas.setText(jtTabel.getValueAt(baris, 4).toString());
            jtfEmail.setText(jtTabel.getValueAt(baris, 5).toString());
            jtfTempatLahir.setText(jtTabel.getValueAt(baris, 6).toString());
            jtaAlamat.setText(jtTabel.getValueAt(baris, 7).toString());
        }
    }//GEN-LAST:event_jtTabelMouseClicked

    private void jbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_jbRefreshActionPerformed

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        // TODO add your handling code here:
        int baris = jtTabel.getSelectedRow();
        if (baris != -1) {
            String NIS = jtTabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbDeleteActionPerformed

    private void jbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearActionPerformed
        // TODO add your handling code here:
        Date date = null;
        jtfNama.setText("");
        jtfNIS.setText("");
        jtfKelas.setText("");
        jtfEmail.setText("");
        jtaAlamat.setText("");
        jtfTempatLahir.setText("");
        jdcTanggalLahir.setDate(date);
        bgJK.clearSelection();
    }//GEN-LAST:event_jbClearActionPerformed

    private void jbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(jdcTanggalLahir.getDate());
        if ("".equals(jtfNIS.getText()) || "".equals(jtaAlamat.getText()) || "".equals(jtfKelas.getText()) || "".equals(jtfNama.getText()) || "".equals(jtfEmail.getText()) || tanggal == null || "".equals(jtfTempatLahir.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if (jrbLaki.isSelected()) {
                JK = "L";
            } else {
                JK = "P";
            }
            String SQL = "UPDATE t_siswa SET "
                    + "NamaSiswa='"+jtfNama.getText()+"',"+"JenisKelamin='" + JK + "',"
                    + "Kelas='"+jtfKelas.getText()+"',"+"Email='" + jtfEmail.getText() + "',"
                    + "tanggalLahir='" + tanggal + "'," + "tempatLahir='" + jtfTempatLahir.getText() + "',"
                    + "Alamat='" + jtaAlamat.getText()+"' "
                    + "WHERE NIS='"+jtfNIS.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbEditActionPerformed

    private void jbEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEdit1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}     ");
        try {
            jtTabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jbEdit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgJK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelJam;
    private javax.swing.JLabel jLabelTanggal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbClear;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbEdit;
    private javax.swing.JButton jbEdit1;
    private javax.swing.JButton jbRefresh;
    private javax.swing.JButton jbSave;
    private com.toedter.calendar.JDateChooser jdcTanggalLahir;
    private javax.swing.JRadioButton jrbLaki;
    private javax.swing.JRadioButton jrbPerempuan;
    private javax.swing.JTable jtTabel;
    private javax.swing.JTextArea jtaAlamat;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfKelas;
    private javax.swing.JTextField jtfNIS;
    private javax.swing.JTextField jtfNama;
    private javax.swing.JTextField jtfTempatLahir;
    // End of variables declaration//GEN-END:variables

    private final void selectData() {
        String kolom[] = {"NIS","Nama Siswa","Tanggal Lahir","Jenis Kelamin","Kelas","Email","Tempat Lahir","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String NIS = rs.getString(1);
                String namaSiswa = rs.getString(2);
                String tanggalLahir = rs.getString(3);
                String jenisKelamin = "";
                if ("L".equals(rs.getString(4))) {
                    jenisKelamin = "Laki-laki";
                } else {
                    jenisKelamin = "Perempuan";
                }
                String kelas = rs.getString(5);
                String email = rs.getString(6);
                String tempatLahir = rs.getString(7);
                String alamat = rs.getString(8);
                String data[] = {NIS,namaSiswa,tanggalLahir,jenisKelamin,kelas,email,tempatLahir,alamat};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtTabel.setModel(dtm);
    }
    
    private void setTanggal(){
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kalender = new
            java.text.SimpleDateFormat("dd/MM/yyyy");
        jLabelTanggal.setText(kalender.format(sekarang));
    }
    
    String nolJam = "";
    String nolMenit = "";
    String nolDetik = "";
    
    private void setJam(){
        ActionListener taskPerfomer = (ActionEvent e) -> {
            Date dt = new Date();
            int nilaiJam = dt.getHours();
            int nilaiMenit = dt.getMinutes();
            int nilaiDetik = dt.getSeconds();
            if (nilaiJam <= 9) {
                nolJam = "0";
            }
            if (nilaiMenit <= 9) {
                nolMenit = "0";
            }
            if (nilaiDetik <= 9) {
                nolDetik = "0";
            }
            //Membuat String jam, menit, dan detik
            String jam = nolJam + Integer.toString(nilaiJam);
            String menit = nolMenit + Integer.toString(nilaiMenit);
            String detik = nolDetik + Integer.toString(nilaiDetik);
            jLabelJam.setText("Jam " + jam +":" + menit + ":" + detik);
        };
        new Timer(100, taskPerfomer).start();
    }
}
