
import com.sun.istack.internal.logging.Logger;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.util.logging.PlatformLogger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zhe
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJK = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNIS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jrbLaki = new javax.swing.JRadioButton();
        jrbPerempuan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jtfKelas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaAlamat = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jbSave = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jbClear = new javax.swing.JButton();
        jbRefresh = new javax.swing.JButton();
        jbEdit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Alamat");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 310, 100, 20);

        jtfNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNISActionPerformed(evt);
            }
        });
        jPanel2.add(jtfNIS);
        jtfNIS.setBounds(10, 30, 270, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NIS");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 10, 30, 20);
        jPanel2.add(jtfNama);
        jtfNama.setBounds(10, 90, 270, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nama");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 70, 50, 20);

        bgJK.add(jrbLaki);
        jrbLaki.setText("Laki-laki");
        jPanel2.add(jrbLaki);
        jrbLaki.setBounds(10, 150, 70, 23);

        bgJK.add(jrbPerempuan);
        jrbPerempuan.setText("Perempuan");
        jPanel2.add(jrbPerempuan);
        jrbPerempuan.setBounds(90, 150, 90, 23);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Jenis Kelamin");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 130, 100, 20);
        jPanel2.add(jtfKelas);
        jtfKelas.setBounds(10, 210, 270, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Kelas");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 190, 100, 20);
        jPanel2.add(jtfEmail);
        jtfEmail.setBounds(10, 270, 270, 30);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 250, 100, 20);

        jtaAlamat.setColumns(20);
        jtaAlamat.setRows(5);
        jScrollPane1.setViewportView(jtaAlamat);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 330, 270, 80);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 160, 290, 420);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(null);

        jbSave.setText("Save");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });
        jPanel3.add(jbSave);
        jbSave.setBounds(10, 10, 90, 40);

        jbDelete.setText("Delete");
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(jbDelete);
        jbDelete.setBounds(120, 10, 90, 40);

        jbClear.setText("Clear");
        jbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearActionPerformed(evt);
            }
        });
        jPanel3.add(jbClear);
        jbClear.setBounds(230, 10, 80, 40);

        jbRefresh.setText("Refresh");
        jbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(jbRefresh);
        jbRefresh.setBounds(330, 10, 80, 40);

        jbEdit.setText("Edit");
        jbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditActionPerformed(evt);
            }
        });
        jPanel3.add(jbEdit);
        jbEdit.setBounds(430, 10, 80, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(300, 110, 530, 60);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM BIODATA SISWA SMK TELKOM MALANG");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 570, 29);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("The Real Informatic Schools");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 50, 240, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 100);

        jPanel5.setBackground(new java.awt.Color(102, 255, 102));
        jPanel5.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ISIAN DATA SISWA");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(70, 0, 160, 50);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 109, 290, 50);

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));
        jPanel4.setLayout(null);

        jScrollPane2.setBackground(new java.awt.Color(153, 255, 153));

        jtTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis Kelamin", "Kelas", "Email", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtTabel);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 510, 380);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(300, 180, 530, 400);

        setSize(new java.awt.Dimension(855, 618));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        // TODO add your handling code here:
        if ("".equals(jtfNIS.getText()) || "".equals(jtaAlamat.getText()) || "".equals(jtfKelas.getText()) || "".equals(jtfNama.getText()) || "".equals(jtfEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if (jrbLaki.isSelected()) {
                JK = "L";
            } else {
                JK = "P";
            }
            String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat) "
                    + "VALUES('" + jtfNIS.getText() + "','" + jtfNama.getText() + "','" + JK + "','"
                    + jtfKelas.getText() + "','" +jtfEmail.getText() + "','" + jtaAlamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbSaveActionPerformed

    private void jtfNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNISActionPerformed

    private void jtTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelMouseClicked
        // TODO add your handling code here:
        int baris = jtTabel.getSelectedRow();
        if (baris != -1) {
            jtfNIS.setText(jtTabel.getValueAt(baris, 0).toString());
            jtfNama.setText(jtTabel.getValueAt(baris, 1).toString());
            if ("Laki-laki".equals(jtTabel.getValueAt(baris, 2).toString())) {
                jrbLaki.setSelected(true);
            } else {
                jrbPerempuan.setSelected(true);
            }
            jtfKelas.setText(jtTabel.getValueAt(baris, 3).toString());
            jtfEmail.setText(jtTabel.getValueAt(baris, 4).toString());
            jtaAlamat.setText(jtTabel.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_jtTabelMouseClicked

    private void jbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_jbRefreshActionPerformed

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        // TODO add your handling code here:
        int baris = jtTabel.getSelectedRow();
        if (baris != -1) {
            String NIS = jtTabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbDeleteActionPerformed

    private void jbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearActionPerformed
        // TODO add your handling code here:
        jtfNama.setText("");
        jtfNIS.setText("");
        jtfKelas.setText("");
        jtfEmail.setText("");
        jtaAlamat.setText("");
        bgJK.clearSelection();
    }//GEN-LAST:event_jbClearActionPerformed

    private void jbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditActionPerformed
        // TODO add your handling code here:
        if ("".equals(jtfNIS.getText()) || "".equals(jtaAlamat.getText()) || "".equals(jtfKelas.getText()) || "".equals(jtfNama.getText()) || "".equals(jtfEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if (jrbLaki.isSelected()) {
                JK = "L";
            } else {
                JK = "P";
            }
            String SQL = "UPDATE t_siswa SET "
                    + "NamaSiswa='"+jtfNama.getText()+"',"+"JenisKelamin='" + JK + "',"
                    + "Kelas='"+jtfKelas.getText()+"',"+"Email='" + jtfEmail.getText() + "',"
                    + "Alamat='" + jtaAlamat.getText()+"' "
                    + "WHERE NIS='"+jtfNIS.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgJK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbClear;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbEdit;
    private javax.swing.JButton jbRefresh;
    private javax.swing.JButton jbSave;
    private javax.swing.JRadioButton jrbLaki;
    private javax.swing.JRadioButton jrbPerempuan;
    private javax.swing.JTable jtTabel;
    private javax.swing.JTextArea jtaAlamat;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfKelas;
    private javax.swing.JTextField jtfNIS;
    private javax.swing.JTextField jtfNama;
    // End of variables declaration//GEN-END:variables

    public void selectData() {
        String kolom[] = {"NIS","Nama Siswa","Jenis Kelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String NIS = rs.getString(1);
                String namaSiswa = rs.getString(2);
                String jenisKelamin = "";
                if ("L".equals(rs.getString(3))) {
                    jenisKelamin = "Laki-laki";
                } else {
                    jenisKelamin = "Perempuan";
                }
                String kelas = rs.getString(4);
                String email = rs.getString(5);
                String alamat = rs.getString(6);
                String data[] = {NIS,namaSiswa,jenisKelamin,kelas,email,alamat};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtTabel.setModel(dtm);
    }
}
